CREATE TABLE IF NOT EXISTS BASIC_PROFILE (
PLAYER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
PLAYER_NAME CHAR(50) NOT NULL,
DATE_OF_BIRTH CHAR(50),
HEIGHT CHAR(10),
WEIGHT REAL,
FROM_YEAR INT,
TO_YEAR INT,
POSITION CHAR(10),
SHOOTS CHAR(10),
COLLEGE CHAR(100),
URL CHAR(500)
);