CREATE TABLE IF NOT EXISTS BASIC_FRANCHISE_INFO(
LEAGUE CHAR(10),
FROM_YEAR INT,
GAMES INT,
LOSSES INT,
TO_YEAR INT,
PLAYOFFS INT,
WINS INT,
DIVISION_WINS INT,
YEARS INT,
CHAMPIONSHIP_WINS INT,
CONFERENCE_WINS INT,
WIN_LOSS_PERCENTAGE REAL,
FRANCHISE_NAME CHAR(50)
)