CREATE TABLE IF NOT EXISTS SEASONS_FRANCHISES(
LEAGUE CHAR(5),
DEF_RATING REAL,
FINISH INTEGER,
PLAYOFFS CHAR(70),
REL_DEF_RATING REAL,
PACE REAL,
SEASON CHAR(10),
COACHES CHAR(70),
WIN_LOSS REAL,
LOSS REAL,
SRS_RATING REAL,
REL_OFF_RATING REAL,
TOP_WS CHAR(35),
WINS INTEGER,
TEAM CHARACTER(55),
OFF_RATING REAL,
REL_PLACE REAL
);
