INSERT INTO  BASIC_FRANCHISE_INFO(
LEAGUE,
FROM_YEAR,
GAMES,
LOSSES,
TO_YEAR,
PLAYOFFS,
WINS,
DIVISION_WINS,
YEARS,
CHAMPIONSHIP_WINS,
CONFERENCE_WINS,
WIN_LOSS_PERCENTAGE,
FRANCHISE_NAME
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)