INSERT INTO PLAYERS_TOTALS(PLAYER_ID, SEASON, AGE, TEAM, LEAGUE, POSITION, GAMES, GAMES_STARTED,
MINUTES_PLAYED, FIELD_GOALS, FIELD_GOALS_ATTEMPTS, THREE_POINTS_FG, THREE_POINTS_FG_ATTEMPTS, TWO_POINTS_FG,
TWO_POINTS_FG_ATTEMPTS, EFF_FIELD_GOAL_PERCENT, FREE_THROWS, FREE_THROWS_ATTEMPTS, OFFESNIVE_REBOUNDS,
DEFENSIVE_REBOUNDS, ASSISTS, STEALS, BLOCKS, TURNOVERS, PERSONAL_FOULS, POINTS)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)