/* CONSIDERING ONLY THE PAST 5 YEARS PERFORMANCE*/
DROP TABLE IF EXISTS PF_PREVIOUS5_SEASONS_TEMP;
CREATE TABLE PF_PREVIOUS5_SEASONS_TEMP AS

SELECT * FROM T_TBL_PLAYERS_TOTALS
WHERE PLAYER_ID IN(
SELECT DISTINCT(PLAYER_ID) FROM T_TBL_PLAYERS_TOTALS
WHERE POSITION IN ('PF', 'PF-PG', 'PF-SG', 'PF-C', 'PF-SF')
) AND SEASON_ID IN (SELECT SEASON_ID FROM T_TBL_SEASON
					WHERE SEASON IN('2014-15', '2013-14', '2012-13', '2011-12', '2010-11'));

DROP TABLE IF EXISTS TEMP_PLAYER_UNIQUE;
CREATE TABLE TEMP_PLAYER_UNIQUE AS 
SELECT PLAYER_ID,SEASON_ID, MAX(GAMES) AS GAMES FROM PF_PREVIOUS5_SEASONS_TEMP GROUP BY PLAYER_ID, SEASON_ID;

DROP TABLE IF EXISTS PF_PREVIOUS5_SEASONS;
CREATE TABLE PF_PREVIOUS5_SEASONS AS
SELECT PF_PREVIOUS5_SEASONS_TEMP.* FROM PF_PREVIOUS5_SEASONS_TEMP, TEMP_PLAYER_UNIQUE
WHERE PF_PREVIOUS5_SEASONS_TEMP.PLAYER_ID = TEMP_PLAYER_UNIQUE.PLAYER_ID
AND PF_PREVIOUS5_SEASONS_TEMP.SEASON_ID = TEMP_PLAYER_UNIQUE.SEASON_ID
AND PF_PREVIOUS5_SEASONS_TEMP.GAMES = TEMP_PLAYER_UNIQUE.GAMES;

DROP TABLE IF EXISTS PF_PREVIOUS5YEARS;
CREATE TABLE PF_PREVIOUS5YEARS AS 
SELECT PF_PREVIOUS5_SEASONS.*, PLAYER_SALARY_PER_SEASON.SALARY
FROM PF_PREVIOUS5_SEASONS, PLAYER_SALARY_PER_SEASON
WHERE PF_PREVIOUS5_SEASONS.PLAYER_ID == PLAYER_SALARY_PER_SEASON.PLAYER_ID
AND PF_PREVIOUS5_SEASONS.SEASON_ID == PLAYER_SALARY_PER_SEASON.SEASON_ID;

DROP TABLE IF EXISTS PF_PREVIOUS5_SEASONS;
DROP TABLE PF_PREVIOUS5_SEASONS_TEMP;
DROP TABLE TEMP_PLAYER_UNIQUE;
/*
	PREVIOUS 5 YEARS AVERAGE FOR POINT GUARDS 
*/
DROP TABLE IF EXISTS PF_PREVIOUS5YEARS_AVERAGE;
CREATE TABLE PF_PREVIOUS5YEARS_AVERAGE AS
SELECT PLAYER_ID,
AVG(GAMES) AS GAMES,
AVG(GAMES_STARTED) AS GAMES_STARTED,
AVG(MINUTES_PLAYED) AS MINUTES_PLAYED,
AVG(TWO_POINTS_FG) AS TWO_POINTS_FG,
AVG(TWO_POINTS_FG_ATTEMPTS) AS TWO_POINTS_FG_ATTEMPTS,
EFF_FIELD_GOAL_PERCENT,
AVG(OFFESNIVE_REBOUNDS) AS OFFENSIVE_REBOUNDS,
AVG(DEFENSIVE_REBOUNDS) AS DEFENSIVE_REBOUNDS,
AVG(BLOCKS) AS BLOCKS,
AVG(POINTS) AS POINTS,
AVG(SALARY) AS SALARY 
FROM PF_PREVIOUS5YEARS
GROUP BY PLAYER_ID;
