/*
	If they have played for two teams in the same season then calculate the sum 
*/
DROP TABLE IF EXISTS PLAYER_SALARY_PER_SEASON;
CREATE TABLE PLAYER_SALARY_PER_SEASON AS
SELECT PLAYER_ID, T_TBL_SEASON.SEASON AS SEASON, T_TBL_SEASON.SEASON_ID AS SEASON_ID, SUM(SALARY) AS SALARY, TEAM FROM PLAYER_SALARY, T_TBL_SEASON
WHERE PLAYER_SALARY.SEASON = T_TBL_SEASON.SEASON
GROUP BY PLAYER_ID, PLAYER_SALARY.SEASON;