/* CONSIDERING ONLY THE PAST 5 YEARS PERFORMANCE*/
DROP TABLE IF EXISTS SG_PREVIOUS5_SEASONS_TEMP;
CREATE TABLE SG_PREVIOUS5_SEASONS_TEMP AS
SELECT * FROM T_TBL_PLAYERS_TOTALS
WHERE PLAYER_ID IN(
SELECT DISTINCT(PLAYER_ID) FROM T_TBL_PLAYERS_TOTALS
WHERE POSITION IN ('SG','SG-SF', 'SG-PG', 'SG-PF')
) AND SEASON_ID IN (SELECT SEASON_ID FROM T_TBL_SEASON
					WHERE SEASON IN('2014-15', '2013-14', '2012-13', '2011-12', '2010-11'));

DROP TABLE IF EXISTS TEMP_PLAYER_UNIQUE;
CREATE TABLE TEMP_PLAYER_UNIQUE AS 
SELECT PLAYER_ID,SEASON_ID, MAX(GAMES) AS GAMES FROM SG_PREVIOUS5_SEASONS_TEMP GROUP BY PLAYER_ID, SEASON_ID;

DROP TABLE IF EXISTS SG_PREVIOUS5_SEASONS;
CREATE TABLE SG_PREVIOUS5_SEASONS AS
SELECT SG_PREVIOUS5_SEASONS_TEMP.* FROM SG_PREVIOUS5_SEASONS_TEMP, TEMP_PLAYER_UNIQUE
WHERE SG_PREVIOUS5_SEASONS_TEMP.PLAYER_ID = TEMP_PLAYER_UNIQUE.PLAYER_ID
AND SG_PREVIOUS5_SEASONS_TEMP.SEASON_ID = TEMP_PLAYER_UNIQUE.SEASON_ID
AND SG_PREVIOUS5_SEASONS_TEMP.GAMES = TEMP_PLAYER_UNIQUE.GAMES;

DROP TABLE IF EXISTS SG_PREVIOUS5YEARS;
CREATE TABLE SG_PREVIOUS5YEARS AS 
SELECT SG_PREVIOUS5_SEASONS.*, PLAYER_SALARY_PER_SEASON.SALARY
FROM SG_PREVIOUS5_SEASONS, PLAYER_SALARY_PER_SEASON
WHERE SG_PREVIOUS5_SEASONS.PLAYER_ID == PLAYER_SALARY_PER_SEASON.PLAYER_ID
AND SG_PREVIOUS5_SEASONS.SEASON_ID == PLAYER_SALARY_PER_SEASON.SEASON_ID;

DROP TABLE IF EXISTS SG_PREVIOUS5_SEASONS;
DROP TABLE SG_PREVIOUS5_SEASONS_TEMP;
DROP TABLE TEMP_PLAYER_UNIQUE;

/*
	Taking the average of the previous 5 years 
*/
DROP TABLE IF EXISTS SG_PREVIOUS5YEARS_AVERAGE;
CREATE TABLE SG_PREVIOUS5YEARS_AVERAGE AS
SELECT PLAYER_ID, AVG(GAMES) AS GAMES, AVG(GAMES_STARTED) AS GAMES_STARTED, AVG(MINUTES_PLAYED) MINUTES_PLAYED, AVG(FIELD_GOALS) AS FIELD_GOALS, AVG(FIELD_GOALS_ATTEMPTS) AS FIELD_GOALS_ATTEMPTS, AVG(THREE_POINTS_FG) AS THREE_POINTS_FG, AVG(THREE_POINTS_FG_ATTEMPTS) AS THREE_POINTS_FG_ATTEMPTS, AVG(TWO_POINTS_FG) AS TWO_POINTS_FG,
AVG(TWO_POINTS_FG_ATTEMPTS) AS TWO_POINTS_FG_ATTEMPTS, EFF_FIELD_GOAL_PERCENT, AVG(FREE_THROWS) AS FREE_THROWS, AVG(FREE_THROWS_ATTEMPTS) AS FREE_THROWS_ATTEMPTS,
AVG(ASSISTS) AS ASSISTS, AVG(TURNOVERS) AS TURNOVERS, AVG(POINTS) AS POINTS, AVG(SALARY) AS SALARY FROM SG_PREVIOUS5YEARS
GROUP BY PLAYER_ID;





